# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cameron Monagle
email: cameron.jm@gmail.com
description: Montreal Web Developer, progressive activist, and techy-type.
biography: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Cameron Monagle. I'm a Toronto base front-end web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cameronmonagle.com" # the base hostname & protocol for your site
twitter_username: cmonagle
github_username:  cmonagle
linkedin_username:  cmonagle

# Build settings
markdown: kramdown
